### ISSUE TITLE
Update zazu-apps easy as install

### ISSUE THREAD

**Issue by Schubidu** [zazujs/zazu#1]
Please make it possible to update zazu-apps easy as install zazu-apps.

**Comment by apinnecke** [comment]
First Savanna change providing the api endpoint: https://github.com/zazujs/savanna/commit/e8b8c04505c7c455aa6f0b10142f03876f6cea13#diff-925810ecb92216fdf03bb8899c9ea59dR8

**Comment by apinnecke** [comment]
Zazu implementation done in https://github.com/zazujs/zazu/commit/0fca3c7eaebb5ad52ad325b84f7725603418fa63#diff-2b85912d575bc6b042645830c7a0f135R58.
